---
swagger: "2.0"
info:
  x-ibm-name: "financing"
  title: "financing"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/financing"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - map:
        title: "financing: input"
        inputs:
          Amount:
            schema:
              type: "number"
            variable: "request.parameters.Amount"
          duration:
            schema:
              type: "integer"
            variable: "request.parameters.duration"
          rate:
            schema:
              type: "number"
            variable: "request.parameters.rate"
        outputs:
          body:
            schema:
              $ref: "#/x-ibm-configuration/targets/financingService/definitions/financingInput"
            variable: "message.body"
            content: "application/xml"
          content-type:
            schema:
              type: "string"
            variable: "message.headers.content-type"
          SOAPAction:
            schema:
              type: "string"
            variable: "message.headers.SOAPAction"
        actions:
        - set: "content-type"
          default: "text/xml"
        - set: "SOAPAction"
          default: "http://thinkibm-services.mybluemix.net/financing"
        - set: "body.Envelope.Body.financingRequest.amount"
          from: "Amount"
        - set: "body.Envelope.Body.financingRequest.duration"
          from: "duration"
        - set: "body.Envelope.Body.financingRequest.rate"
          from: "rate"
    - invoke:
        title: "financing: invoke"
        target-url: "https://thinkibm-services.mybluemix.net/financing/calculate"
        timeout: 60
        verb: "POST"
        cache-response: "protocol"
        cache-ttl: 900
        output: "financingOut"
    - map:
        title: "financing: output"
        inputs:
          input:
            schema:
              $ref: "#/x-ibm-configuration/targets/financingService/definitions/financingOutput"
            variable: "financingOut.body"
            content: "application/xml"
        outputs:
          response:
            schema:
              $ref: "#/definitions/paymentAmount"
            variable: "message.body"
            content: "application/json"
        actions:
        - set: "response.paymentAmount"
          from: "input.Envelope.Body.financingResult.paymentAmount"
  phase: "realized"
  targets:
    financingService:
      swagger: "2.0"
      info:
        title: "financingService"
        description: ""
        x-ibm-name: "financingservice"
        version: "1.0.0"
      schemes:
      - "https"
      basePath: "/financingService"
      produces:
      - "application/xml"
      consumes:
      - "text/xml"
      securityDefinitions:
        clientID:
          type: "apiKey"
          name: "X-IBM-Client-Id"
          in: "header"
          description: ""
      security:
      - clientID: []
      x-ibm-configuration:
        type: "wsdl"
        wsdl-definition:
          wsdl: "5a4b36a90cf236acd5908bab"
          service: "financingService"
          port: "financingPort"
          soap-version: "1.1"
        assembly:
          execute:
          - proxy:
              title: "proxy"
              target-url: "https://thinkibm-services.mybluemix.net/financing/calculate"
        gateway: "datapower-gateway"
        enforced: true
        testable: true
        phase: "realized"
        cors:
          enabled: true
      paths:
        /financing:
          post:
            summary: "Operation financing"
            description: ""
            operationId: "financing"
            x-ibm-soap:
              soap-action: "http://thinkibm-services.mybluemix.net/financing"
              soap-operation: "{http://thinkibm-services.mybluemix.net}financingRequest"
            parameters:
            - in: "body"
              name: "body"
              required: true
              schema:
                $ref: "#/x-ibm-configuration/targets/financingService/definitions/financingInput"
            responses:
              default:
                description: ""
                schema:
                  $ref: "#/x-ibm-configuration/targets/financingService/definitions/financingOutput"
      definitions:
        Security:
          xml:
            namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
            prefix: "wsse"
          type: "object"
          properties:
            UsernameToken:
              xml:
                namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
                prefix: "wsse"
              type: "object"
              properties:
                Username:
                  xml:
                    namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
                    prefix: "wsse"
                  type: "string"
                Password:
                  xml:
                    namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
                    prefix: "wsse"
                  type: "string"
                Nonce:
                  xml:
                    namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
                    prefix: "wsse"
                  type: "string"
                  properties:
                    EncodingType:
                      xml:
                        namespace: ""
                        attribute: true
                      type: "string"
                Created:
                  xml:
                    namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                    prefix: "wsu"
                  type: "string"
            Timestamp:
              xml:
                namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                prefix: "wsu"
              type: "object"
              properties:
                Created:
                  xml:
                    namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                    prefix: "wsu"
                  type: "string"
                Expires:
                  xml:
                    namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                    prefix: "wsu"
                  type: "string"
                Id:
                  xml:
                    namespace: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                    prefix: "wsu"
                    attribute: true
                  type: "string"
        financingInput:
          type: "object"
          properties:
            Envelope:
              xml:
                prefix: "soapenv"
                namespace: "http://schemas.xmlsoap.org/soap/envelope/"
              type: "object"
              properties:
                Header:
                  $ref: "#/x-ibm-configuration/targets/financingService/definitions/financingHeader"
                Body:
                  type: "object"
                  properties:
                    financingRequest:
                      $ref: "#/x-ibm-configuration/targets/financingService/definitions/financingRequest_ser"
                  required:
                  - "financingRequest"
              required:
              - "Body"
          required:
          - "Envelope"
          example: "\n<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\
            >\n <soapenv:Header>\n  <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"\
            \ xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\"\
            >\n   <wsse:UsernameToken>\n    <wsse:Username>string</wsse:Username>\n\
            \    <wsse:Password>string</wsse:Password>\n    <wsse:Nonce EncodingType=\"\
            string\">string</wsse:Nonce>\n    <wsu:Created>string</wsu:Created>\n\
            \   </wsse:UsernameToken>\n   <wsu:Timestamp wsu:Id=\"string\">\n    <wsu:Created>string</wsu:Created>\n\
            \    <wsu:Expires>string</wsu:Expires>\n   </wsu:Timestamp>\n  </wsse:Security>\n\
            \ </soapenv:Header>\n <soapenv:Body>\n  <ser:financingRequest xmlns:ser=\"\
            http://thinkibm-services.mybluemix.net\"><!-- mandatory -->\n   <ser:amount><!--\
            \ mandatory -->3</ser:amount>\n   <ser:duration><!-- mandatory -->3</ser:duration>\n\
            \   <ser:rate><!-- mandatory -->3</ser:rate>\n  </ser:financingRequest>\n\
            \ </soapenv:Body>\n</soapenv:Envelope>"
        financingHeader:
          type: "object"
          properties:
            Security:
              $ref: "#/x-ibm-configuration/targets/financingService/definitions/Security"
        financingOutput:
          type: "object"
          properties:
            Envelope:
              xml:
                prefix: "soapenv"
                namespace: "http://schemas.xmlsoap.org/soap/envelope/"
              type: "object"
              properties:
                Body:
                  type: "object"
                  properties:
                    financingResult:
                      $ref: "#/x-ibm-configuration/targets/financingService/definitions/financingResult_ser"
              required:
              - "Body"
          required:
          - "Envelope"
          example: "\n<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\
            >\n <soapenv:Body>\n  <ser:financingResult xmlns:ser=\"http://thinkibm-services.mybluemix.net\"\
            >\n   <ser:paymentAmount><!-- mandatory -->3</ser:paymentAmount>\n  </ser:financingResult>\n\
            \ </soapenv:Body>\n</soapenv:Envelope>"
        financingRequest_ser:
          xml:
            namespace: "http://thinkibm-services.mybluemix.net"
            prefix: "ser"
          type: "object"
          properties:
            amount:
              type: "number"
            duration:
              type: "number"
            rate:
              type: "number"
          required:
          - "amount"
          - "duration"
          - "rate"
          example: "\n<ser:financingRequest xmlns:ser=\"http://thinkibm-services.mybluemix.net\"\
            >\n <ser:amount><!-- mandatory -->3</ser:amount>\n <ser:duration><!--\
            \ mandatory -->3</ser:duration>\n <ser:rate><!-- mandatory -->3</ser:rate>\n\
            </ser:financingRequest>"
        financingResult_ser:
          xml:
            namespace: "http://thinkibm-services.mybluemix.net"
            prefix: "ser"
          type: "object"
          properties:
            paymentAmount:
              type: "number"
          required:
          - "paymentAmount"
          example: "\n<ser:financingResult xmlns:ser=\"http://thinkibm-services.mybluemix.net\"\
            >\n <ser:paymentAmount><!-- mandatory -->3</ser:paymentAmount>\n</ser:financingResult>"
paths:
  /calculate:
    get:
      responses:
        200:
          description: "200 OK"
          schema:
            $ref: "#/definitions/paymentAmount"
    parameters:
    - name: "Amount"
      type: "number"
      required: true
      in: "query"
      format: "float"
    - name: "duration"
      type: "integer"
      required: true
      in: "query"
      format: "int32"
    - name: "rate"
      type: "number"
      required: true
      in: "query"
      format: "float"
definitions:
  paymentAmount:
    properties:
      paymentAmount:
        type: "number"
        format: "float"
        example: 199.9
        description: "monthly payment"
    additionalProperties: false
    description: "Monthly payment Amount"
    required:
    - "paymentAmount"
tags: []
